#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
/usr/bin/feh --bg-fill ~/Fondos/fingolfin_and_melkor_2.png
~/.config/polybar/launch.sh &
/usr/bin/picom --config ~/.config/picom/picom.conf &
/usr/bin/xbindkeys &
redshift -c ~/.config/redshift/redshift.conf &
#~/scripts/bar/audio_bluetooth.sh &
~/scripts/bar/audio_bar.sh &
~/scripts/bar/brightness_bar.sh &
/usr/bin/unclutter --timeout 0.33 --jitter 0 --ignore-scrolling &
~/scripts/toggling/toggle_touchpad.sh &
